config/routes.rb
SocialAddressbook::Application.routes.draw do
  resources :authentications

  resources :user_data

  get "pages/profile"

  resources :welcomes

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :groups do
    member do
      get 'join'
      post 'join_save'
      get 'invite'
      post 'invite_save'
    end
  end

  authenticated :user do
    root :to => "groups#index"
  end
  devise_for :users do
    get "/", :to => "devise/sessions#new"
  end
  root :to => "devise/sessions#new"

  match ':controller(/:action(/:id(.:format)))'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :groups_users
  has_many :users, :through => :groups_users
  has_many :groups_offline_users
  has_many :offline_users, :through => :groups_offline_users
  belongs_to :owner, :class_name => "User" 

  validates :name, :presence => true, :length => { :minimum => 3 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  check_authorization
  load_and_authorize_resource

  # GET /groups
  # GET /groups.xml
  def index
    if Rails.configuration.database_configuration[Rails.env]["adapter"]=='sqlite3'
      @groups = current_user.groups.where("private != 0 AND owner_id != ?", current_user.id)
    else
      @groups = current_user.groups.where("private IS FALSE AND owner_id <> ?", current_user.id)
    end
    @my_groups = current_user.groups.where(:owner_id => current_user.id)


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/invite
  # GET /groups/invite.xml
  def invite
    @group = Group.find(params[:id])
    @offline_user = OfflineUser.new
    @user_datum = OfflineUserDatum.new

    respond_to do |format|
      format.html # invite.html.erb
      format.xml  { render :xml => @offline_user }
    end
  end

  # POST /groups/1/invite_save
  def invite_save
    @group = Group.find(params[:id])

    # Check if the invited user is already registered in the system
    if UserDatum.where(:value => params[:user_datum][:value], :data_type_id => params[:user_datum][:data_type_id]).count > 0

      # In this case we add the associated person to the clique
      @user_datum = UserDatum.where(:value => params[:user_datum][:value], :data_type_id => params[:user_datum][:data_type_id]).first
      @invitee = @user_datum.user
      GroupsUser.create(:user => @invitee, :group => @group)

      # We also want to notify the user that he was added to the clique
      if @invitee.has_datum_of_type('Email')
        InviteMailer.send_invitation(current_user, @invitee, @group).deliver  
      end
      
      # We need a dummy offline user to keep the viewer happy
      @offline_user = OfflineUser.new
    else

      # Otherwise, we create an offline account for this user 
      @offline_user = OfflineUser.create(:name => params[:user_datum][:name]) # This is a hack to avoid multiple forms on one page: use the name parameter for a second UserDatum of type name
      # Add the personal information to this user
      @user_datum = OfflineUserDatum.new(params[:user_datum])
      @user_datum.data_type_id = params[:user_datum][:data_type_id]
      @user_datum.offline_user_id = @offline_user.id
      
      if @user_datum.save
        # In case an email was provided, we also send an email invitation to join incliques
        if @user_datum.data_type.name == 'Email'
          InviteMailer.send_invitation(current_user, @offline_user, @group).deliver
        end
      end

      # And add him to the clique
      GroupsOfflineUser.create(:offline_user => @offline_user, :group => @group)

    end

    respond_to do |format|
      if @user_datum.errors.length.zero?
        format.html { redirect_to(invite_group_path(@group), :notice => 'Person succesfully invited.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        # Something went wrong, so let's get rid of the offline user and its associated data again
        @offline_user.destroy

        format.html { render :action => "invite" }
        format.xml  { render :xml => @user_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /groups/join
  # GET /groups/join.xml
  def join
    @groups_user = GroupsUser.new

    respond_to do |format|
      format.html # join.html.erb
      format.xml  { render :xml => @groups_user }
    end
  end

  # POST /groups/1/join_save
  def join_save
    @group = Group.find(params[:id])
    @groups_user = GroupsUser.new(params[:group])
    @groups_user.user = current_user
    @groups_user.group = @group 

    @groups_user.user = current_user
    @groups_user.group = @group

    respond_to do |format|
      if @groups_user.save
        format.html { redirect_to(@group, :notice => 'You joined the group.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "join" }
        format.xml  { render :xml => @groups_user.errors, :status => :unprocessable_entity }
      end
    end
  end


  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])
    @group.owner = current_user

    respond_to do |format|
      if @group.save
        # We make the owner part of the group
        GroupsUser.create(:user => current_user, :group => @group)
    
        format.html { redirect_to(invite_group_path(@group)) }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(groups_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this clique from being saved:</h2>

    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= semantic_form_for(@group) do |f| %>
  <%= f.inputs :name %>
  <%= f.buttons do %>
    <%= f.commit_button "Create Clique" %>
  <% end %>
<% end %>

app/views/groups/_invite_form.html.erb
<% if @offline_user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@offline_user.errors.count, "error") %> prohibited this person from being invited into this clique:</h2>

    <ul>
    <% @offline_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @user_datum.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_datum.errors.count, "error") %> prohibited this person from being invited into this clique:</h2>

    <ul>
    <% @user_datum.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= semantic_form_for(:user_datum, :url => { :class => "group", :action => "invite_save" }) do |f| %>
  <%= f.input :name, :label => "Name" %>
  <%= f.inputs :class => 'inline_fields' do%>
    <%= f.input :data_type_id, :label => "Type", :as => :select, :collection => DataType.find(:all), :prompt => "[select type]", :wrapper_html => { :class => "left" } %>
    <%= f.input :value, :class => "right", :label => "Address", :wrapper_html => { :class => "left" } %>
  <% end %>
  <%= f.commit_button :label => "Invite to clique" %>
<% end %>

app/views/groups/_join_form.html.erb
<%= semantic_form_for(:groups_user, :url => { :class => "group", :action => "join_save" }) do |f| %>
  <% if @groups_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groups_user.errors.count, "error") %> prohibited this user from joining this group:</h2>

      <ul>
      <% @groups_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :permission_email, :as => :boolean, :label => "Share e-mail?" %>
  <%= f.input :permission_phone_number, :as => :boolean, :label => "Share phone_number?" %>
  <%= f.commit_button :label => "Join clique", :button_html => { :class => "button primary" } %>

<% end %>

app/views/groups/edit.html.erb
<h2>Editing group</h2>

<%= render 'form' %>

app/views/groups/index.html.erb
<h2>My cliques</h2>
<table>
<% if @my_groups.empty? %>
  You don't have any Cliques yet, but why don't you just <%= link_to "create one?", new_group_path %>
<% end %>
<% @my_groups.each do |group| %>
  <tr>
    <td>
      <%= link_to group.name, group_path(group) %>
    </td>
    <td>
        <% if group.owner == current_user %>
        <% end %>
    </td>
    </tr>
  <% end %>
</table>

<% if not @groups.empty? %>
  </br>

  <h2>Other cliques</h2>
  <table>
  <% @groups.each do |group| %>
    <tr>
      <td>
        <%= link_to group.name, group_path(group) %>
      </td>
      <td>
          <% if group.owner == current_user %>
          <% end %>
      </td>
      </tr>
    <% end %>

  </table>
<% end %>

app/views/groups/invite.html.erb
<h2>Invite members</h2>

<%= render 'invite_form' %>

<% if (@group.offline_users.count + @group.users.count) > 1 %>
  </br>
  </br>
  <h3>Invited members:</h3> 

  <% @group.offline_users.each do |offline_user| %>
    <%= offline_user.name %> (<%= offline_user.offline_user_data.first.value %>)</br>
  <% end %>

  <% @group.users.each do |user| %>
    <% if user != current_user %>
      <%= user.name %> (<%= user.email %>) </br>
    <% end %>
  <% end %>
<% end %>

<p><%= link_to 'Finish', group_path %></p>

app/views/groups/join.html.erb
<h2>Join clique</h2>

<%= render 'join_form' %>

app/views/groups/new.html.erb
<h2>New clique</h2>

<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h2>Clique name:</h2>
  <%= @group.name %>
<%= link_to 'Edit', edit_group_path(@group), :class => 'button primary icon edit' %>
<%= link_to 'Delete group', @group, :confirm => 'Are you sure?', :method => :delete, :class => 'button primary danger icon remove' %>

</p>

<!--  
<p><b>Invitation link:</b>  <%= link_to join_group_url(@group), join_group_path(@group) %> <i>Share this URL to invite people to join your clique</i>
</p> -->

</br>

<h3>Verified members</h3>
<% @group.users.each do |user| %>
  Name: <%= user.name %></br>
  Details:
  <% user.user_data.each do |user_data| %>
    <%= user_data.name %> <%= user_data.data_type.name %>: <%= user_data.value %>
    <br>
   <% end %>
   </br>
   </br>
<% end %>

<p>

</br>

<h3>Unverified members</h3>
<% @group.offline_users.each do |user| %>
  <%= user.name %>
  <% user.offline_user_data.each do |user_data| %>
    (<%= user_data.value %>)
    <br>
  <% end %>

   </br>
   </br>
<% end %>

<p>

<%= link_to 'Invite more people', invite_group_path(@group), :class => 'button primary icon edit' %>