config/routes.rb
SocialAddressbook::Application.routes.draw do
  resources :authentications

  resources :user_data

  get "pages/profile"

  resources :welcomes

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :groups do
    member do
      get 'join'
      post 'join_save'
      get 'invite'
      post 'invite_save'
    end
  end

  authenticated :user do
    root :to => "groups#index"
  end
  devise_for :users do
    get "/", :to => "devise/sessions#new"
  end
  root :to => "devise/sessions#new"

  match ':controller(/:action(/:id(.:format)))'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/views/layouts/private.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>inCliques</title>
		<%= stylesheet_link_tag :all %>
		<%= stylesheet_link_tag 'formtastic' %>
		<!--[if IE 6]><%= stylesheet_link_tag 'formtastic_ie6' %><![endif]-->
		<!--[if IE 7]><%= stylesheet_link_tag 'formtastic_ie7' %><![endif]-->
		<%= javascript_include_tag :defaults %>
		<%= javascript_include_tag  'jquery' %>
		<%= csrf_meta_tag %>
		<script>
	$(document).ready(function() {
		$('tr').hover(function(){
			$(this).css('background','pink');
		},function(){	
			$(this).css('background','white');
		});
	});
	</script>
<link href='http://fonts.googleapis.com/css?family=Terminal+Dosis:400,700' rel='stylesheet' type='text/css'>
	
	</head>
	<!-- Start of body -->
	<body>
		<!-- Start of top bar -->
		<div id="top-bar">
			<div id="user-info">
				<% if user_signed_in? %>
				Signed in as <b> <%= current_user.email %></b>. Not you?
				<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
				<% end %>
			<br><p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
			</div>
		</div>
		
		<!-- Start of container -->
		<div id="container">
		
			<!-- Start of header -->
			<header>
				<div id="header">
					<div id="logo"><%= image_tag "logo.png", :size => "240x150", :alt => "inCliqu.es", :id => "incliques" %></div>
					<div id="navigation">
						your private community addressbook
					</div>
				</div>
			</header>
			<div id="content-container" class="clearfix">
				<!-- Start of content -->
				<section>
					<div class="side-box side-menu">
						<% if user_signed_in? %>
						  <ul>
							  <li>
								  <%= link_to "My cliques", groups_path %>
							  </li>
							  <li>
								  <%= link_to "Create a Clique", new_group_path %>
							  </li>
							  <li>
								  <%= link_to "My profile", user_data_path %>
							  </li>
						 </ul>
						<% end %>
					</div>

					<div class="main-box">
					<%= yield %>			

					</div>

				</section>
				
				<!-- Start of footer -->
				<footer>
					<div class="wide-box margin-10">
					<a href="http://www.incliqu.es/blog/about-us/">About Us</a> | <a href="http://www.incliqu.es/blog/">Blog</a> | <a href="http://www.incliqu.es/betasignup.php">Sign up for our Beta</a>
					</div>
					
				</footer>
			</div>
		</div>
		<!-- Start of Google Analytics Code -->
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-26378944-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
		<!-- End of Google Analytics Code -->

		<!-- Start of Woopra Code -->
		<script type="text/javascript">
		function woopraReady(tracker) {
		    tracker.setDomain('incliques.heroku.com');
		    tracker.setIdleTimeout(300000);
		    tracker.track();
		    return false;
		}
		(function() {
		    var wsc = document.createElement('script');
		    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
		    wsc.type = 'text/javascript';
		    wsc.async = true;
		    var ssc = document.getElementsByTagName('script')[0];
		    ssc.parentNode.insertBefore(wsc, ssc);
		})();
		</script>
		<!-- End of Woopra Code -->
		
	</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title>inCliques</title>
		<%= stylesheet_link_tag :all %>
		<%= stylesheet_link_tag 'formtastic' %>
		<!--[if IE 6]><%= stylesheet_link_tag 'formtastic_ie6' %><![endif]-->
		<!--[if IE 7]><%= stylesheet_link_tag 'formtastic_ie7' %><![endif]-->
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
		
		<link href='http://fonts.googleapis.com/css?family=Terminal+Dosis:400,700' rel='stylesheet' type='text/css'>
		
	</head>
	<!-- Start of body -->
	<body>
		<!-- Start of top bar -->
		<div id="top-bar">
			<div id="user-info">
				<br /><br />
			</div>
		</div>
		
		<!-- Start of container -->
		<div id="container">
		
			<!-- Start of header -->
			<header>
				<div id="header">
					<div id="logo"><%= image_tag "logo.png", :size => "240x150", :alt => "inCliqu.es", :id => "incliques" %></div>
					<div id="navigation">
						<h2>your private community addressbook</h2>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
						</div>
				<!-- 	<div id="logo-bar">Click to connect via 
						<a href="/auth/viadeo"><%= image_tag "viadeo_32.png", :size => "32x32", :alt => "Viadeo" %></a>
						<a href="/auth/twitter"><%= image_tag "twitter_32.png", :size => "32x32", :alt => "Twitter" %></a>
						</div> -->
				</div>
			</header>
			<div id="content-container" class="clearfix">
				<!-- Start of content -->
				<section>
					<%= yield %>
				</section>
				
				<!-- Start of footer -->
				<footer>
					<div class="wide-box margin-10">
					<a href="http://www.incliqu.es/blog/about-us/">About Us</a> | <a href="http://www.incliqu.es/blog/">Blog</a> | <a href="http://www.incliqu.es/betasignup.php">Sign up for our Beta</a>
					</div>
				</footer>
			</div>
		</div>
		<!-- Start of Google Analytics Code -->
		<script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-26378944-1']);
		  _gaq.push(['_trackPageview']);

		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
		<!-- End of Google Analytics Code -->

		<!-- Start of Woopra Code -->
		<script type="text/javascript">
		function woopraReady(tracker) {
		    tracker.setDomain('incliques.heroku.com');
		    tracker.setIdleTimeout(300000);
		    tracker.track();
		    return false;
		}
		(function() {
		    var wsc = document.createElement('script');
		    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
		    wsc.type = 'text/javascript';
		    wsc.async = true;
		    var ssc = document.getElementsByTagName('script')[0];
		    ssc.parentNode.insertBefore(wsc, ssc);
		})();
		</script>
		<!-- End of Woopra Code -->
	</body>
</html>